ARG BASE_REPOGITORY=junkor1011/jupyter_datascience_spark
# ARG TAG=latest
ARG TAG='2020-07-12'
FROM $BASE_REPOGITORY:$TAG

# PATCH (environment variable)

ENV WORK_DIR=/home/user/work \
    DATA_DIR=/home/user/data \
    LIBS_DIR=/home/user/libs
