ARG BASE_REPOGITORY=junkor1011/jupyter_datascience_spark
# ARG TAG=latest
ARG TAG='2020-07-17_spark24_openj9'
FROM $BASE_REPOGITORY:$TAG

# PATCH (environment variable)

ENV WORK_DIR=/home/user/work \
    DATA_DIR=/home/user/data \
    LIBS_DIR=/home/user/libs

# external libs PATH
ENV PYTHONPATH=$LIBS_DIR/pyspark_utils:$PYTHONPATH

# spark setting
ENV PROJECT_HOME=$WORK_DIR \
    SPARK_WAREHOUSE_HOME=$DATA_DIR/hive-db/spark-warehouse \
    HIVE_METASTORE_DB_HOME=$DATA_DIR/hive-db
